version: 0
run:
  mounts:
  - !mounts.S3Code
    prefix: "s3://{secret.JYNS_AWS_S3_BUCKET}/jaynes-debug"
    local_path: .
    volume: jaynes-mounts
    mount_path: /mnt/jaynes-mounts
    sub_path: "{now:%Y-%m-%d}/{now:%H%M%S.%f}"
    init_image: "episodeyang/jaynes"
    init_image_pull_policy: "IfNotPresent"
    pypath: true
    # needed for credential-less access
    acl: public-read
    # needed for credential-less download
    no_signin: true
    excludes: >-
      --exclude='*__pycache__' --exclude='*.git' --exclude='*.idea' --exclude='*.egg-info'
      --exclude='*.pkl'
    compress: true

  runner: !runners.Container
    # node_selector: null
    name: "jaynes-docker-demo-{now:%H%M%S}-{RUN.count}"
    image: "episodeyang/pytorch"
    image_pull_secret: "dockerhub"
    envs: LANG=utf-8
    # startup: yes | pip install jaynes ml-logger -q
    pypath: "{mounts[0].container_path}"
    workdir: "{mounts[0].container_path}"
    ipc: host
    cpu: 1
    gpu: 1
    gpu_type: "NVIDIA-GeForce-RTX-3090"
    mem: 8Gi
    mem_limit: 8Gi
    volumes:
    - name: jaynes-mounts
      emptyDir:
        medium: Memory
    ttl_seconds_after_finished: 360
  launch: !ENV
    type: Kube
    namespace: <YOUR NAMESPACE HERE>
